### ISSUE TITLE
想问一下这是什么问题

### ISSUE THREAD

**Issue by mjtlyzbsy** [eggggi/pcr_scrimmage#3]
每次选完角色后，游戏正式开始的时候，需要上传图，就会崩溃，这是什么问题
[![2xGKVx.png](https://z3.ax1x.com/2021/06/17/2xGKVx.png)](https://imgtu.com/i/2xGKVx)

**Comment by eggggi** [comment]
可能是账号被风控，尝试换一下发送图片的协议。 __bot__.py 里的 RES_PROTOCOL

**Comment by mjtlyzbsy** [comment]
ok，我试试，非常感谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年6月17日(星期四) 下午4:32
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [eggggi/pcr_scrimmage] 想问一下这是什么问题 (#3)





 
可能是账号被风控，尝试换一下发送图片的协议。 bot.py 里的 RES_PROTOCOL

**Comment by mjtlyzbsy** [comment]
RES_PROTOCOL = 'http'
请问这个要改成什么啊qaq




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "eggggi/pcr_scrimmage"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年6月17日(星期四) 下午4:32
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [eggggi/pcr_scrimmage] 想问一下这是什么问题 (#3)





 
可能是账号被风控，尝试换一下发送图片的协议。 bot.py 里的 RES_PROTOCOL

**Comment by eggggi** [comment]
发送图片的协议
可选 http, file, base64
建议Windows部署使用file协议
建议Linux部署配合本地web server使用http协议
如果你不清楚上面在说什么，请用base64协议（发送大图时可能会失败）

这是hoshino自带的注释，我个人是在windows部署的，所以选 file

**Comment by mjtlyzbsy** [comment]
十分感谢，已经解决问题了




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年6月17日(星期四) 下午4:46
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [eggggi/pcr_scrimmage] 想问一下这是什么问题 (#3)





 
发送图片的协议
 
可选 http, file, base64
 
建议Windows部署使用file协议
 
建议Linux部署配合本地web server使用http协议
 
如果你不清楚上面在说什么，请用base64协议（发送大图时可能会失败）
 
这是hoshino自带的注释，我个人是在windows部署的，所以选 file
