### ISSUE TITLE
大乱斗结束后只有房主获得全部金币

### ISSUE THREAD

**Issue by Damk123** [eggggi/pcr_scrimmage#5]
大佬，我安装步骤装好后，对战结束总是只有房主获得全部金币

**Comment by Damk123** [comment]
还有这个有没有下注的功能

**Comment by eggggi** [comment]
只有房主获得金币的问题是bug，刚刚修复了_(:3)∠)_
并没有下注功能，有空再加_(:3)∠)_

**Comment by Damk123** [comment]
> 只有房主获得金币的问题是bug，刚刚修复了_(:3)∠)_
> 并没有下注功能，有空再加_(:3)∠)_

谢谢大佬，能正常使用了
