### ISSUE TITLE
反馈

### ISSUE THREAD

**Issue by Damk123** [eggggi/pcr_scrimmage#7]
大佬，能不能在每个环节都加一个@所有参与者的功能

**Comment by Damk123** [comment]
还有能不能再添加一个无人加了自动结束的机制

**Comment by eggggi** [comment]
可以的，这些都是我之前想去做但还没有做的功能。。明天就整 \_(:з)∠)\_

**Comment by Damk123** [comment]
> 可以的，这些都是我之前想去做但还没有做的功能。。明天就整 _(:з)∠)_

好的，大佬加油

**Comment by eggggi** [comment]
加完了 \_(:з)∠)\_
