### ISSUE TITLE
在大乱斗开始之后如果不玩不会自动结束

### ISSUE THREAD

**Issue by tang-bai** [eggggi/pcr_scrimmage#8]
在大乱斗开始就是全部玩家确认之后，某个玩家可以一直卡在使用技能那里，这样子游戏进度会直接卡住，希望可以增加一个倒计时什么的

**Comment by eggggi** [comment]
这个可以，记下了 \_(:з」∠)\_

**Comment by tang-bai** [comment]
可以增加一个群主和管理员可以强制结束游戏

**Comment by Ayusummer** [comment]
> 可以增加一个群主和管理员可以强制结束游戏

房主可以用“结束大乱斗”命令结束本局游戏
![image](https://user-images.githubusercontent.com/59549826/122658148-62f10c80-d19c-11eb-8e8d-a81a95db9731.png)

**Comment by eggggi** [comment]
> 在大乱斗开始就是全部玩家确认之后，某个玩家可以一直卡在使用技能那里，这样子游戏进度会直接卡住，希望可以增加一个倒计时什么的

加了 \_(:з」∠)\_
