### ISSUE TITLE
吃货技能描述和使用之后的回复是不一样的

### ISSUE THREAD

**Issue by tang-bai** [eggggi/pcr_scrimmage#9]
技能描述是回复150实际上只有回复100![Inked T4B76CA`7V~@~2%%NV2U(R_LI](https://user-images.githubusercontent.com/71223830/122647297-2ac6db00-d156-11eb-9b26-589791c937df.jpg)

**Comment by eggggi** [comment]
role.py那里写错了，目前这种结构调整数值很容易忘记改描述 \_(:з」∠)\_ 。可以自己改一下，或者等我优化一下结构（可能要大改emmm

**Comment by eggggi** [comment]
改了下佩可的数值，起码能对上描述了。还是不改结构了，好麻烦。。躺平 \_(:з」∠)\_
